// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID        int64
	UserID    int64
	EventID   int64
	Attended  bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Cache struct {
	Key        string
	Value      string
	Expiration int32
}

type CacheLock struct {
	Key        string
	Owner      string
	Expiration int32
}

type Challenge struct {
	ID         int64
	DetailID   int64
	Day        int32
	Difficulty string
}

type Claimed struct {
	ID         int64
	UserID     int64
	TreasureID int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Code struct {
	ID       string
	ImageUrl string
}

type Contribution struct {
	ID        int64
	QuestID   int64
	UserID    int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Detail struct {
	ID          int64
	Name        string
	Description string
	PointGain   int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Event struct {
	ID       int64
	DetailID int64
	CodeID   string
	Location string
	Contact  string
	StartsAt pgtype.Date
	EndsAt   pgtype.Date
}

type FailedJob struct {
	ID         int64
	Uuid       string
	Connection string
	Queue      string
	Payload    string
	Exception  string
	FailedAt   pgtype.Timestamp
}

type Job struct {
	ID          int64
	Queue       string
	Payload     string
	Attempts    int16
	ReservedAt  pgtype.Int4
	AvailableAt int32
	CreatedAt   int32
}

type JobBatch struct {
	ID           string
	Name         string
	TotalJobs    int32
	PendingJobs  int32
	FailedJobs   int32
	FailedJobIds string
	Options      pgtype.Text
	CancelledAt  pgtype.Int4
	CreatedAt    int32
	FinishedAt   pgtype.Int4
}

type Log struct {
	ID        int64
	UserID    int64
	Text      string
	IsSystem  bool
	IsMarked  bool
	IsPrivate bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Memory struct {
	ID          int64
	UserID      int64
	ImageUrl    string
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Migration struct {
	ID        int32
	Migration string
	Batch     int32
}

type Participation struct {
	ID          int64
	ChallengeID int64
	UserID      int64
	MemoryID    int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PasswordResetToken struct {
	Email     string
	Token     string
	CreatedAt pgtype.Timestamp
}

type Profile struct {
	ID         int64
	UserID     int64
	CurrentExp int64
	ExpNeeded  int64
	Points     int64
}

type Quest struct {
	ID              int64
	DetailID        int64
	CodeID          string
	Location        string
	MaxContributors int32
}

type Recap struct {
	ID           int64
	UserID       int64
	Description  string
	TaskFinished int32
	TaskAssigned int32
	Growth       pgtype.Numeric
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Session struct {
	ID           string
	UserID       pgtype.Int8
	IpAddress    pgtype.Text
	UserAgent    pgtype.Text
	Payload      string
	LastActivity int32
}

type Statistic struct {
	ID         int64
	UserID     int64
	Challenges int32
	Events     int32
	Quests     int32
	Treasures  int32
	TreeGrown  int32
}

type Treasure struct {
	ID        int64
	Name      string
	PointGain int64
	CodeID    string
	Claimed   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID              int64
	Name            string
	Username        string
	Email           string
	EmailVerifiedAt pgtype.Timestamp
	Password        string
	IsAdmin         bool
	RememberToken   pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}
