// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attendance struct {
	ID            int64
	UserID        int64
	EventID       int64
	Attended      bool
	ContactNumber string
	CreatedAt     pgtype.Timestamp
	AttendedAt    pgtype.Timestamp
}

type Cache struct {
	Key        string
	Value      string
	Expiration int32
}

type CacheLock struct {
	Key        string
	Owner      string
	Expiration int32
}

type Challenge struct {
	ID         int64
	DetailID   int64
	Day        int32
	Difficulty string
}

type Claimed struct {
	ID         int64
	UserID     int64
	TreasureID int64
	CreatedAt  pgtype.Timestamp
}

type Code struct {
	ID       string
	ImageUrl string
}

type Contribution struct {
	ID        int64
	QuestID   int64
	UserID    int64
	CreatedAt pgtype.Timestamp
}

type Detail struct {
	ID          int64
	Name        string
	Description string
	PointGain   int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Event struct {
	ID        int64
	DetailID  int64
	CodeID    string
	Location  string
	Latitude  float64
	Longitude float64
	Contact   string
	StartsAt  pgtype.Timestamp
	EndsAt    pgtype.Timestamp
	CoverKey  pgtype.Text
}

type FailedJob struct {
	ID         int64
	Uuid       string
	Connection string
	Queue      string
	Payload    string
	Exception  string
	FailedAt   pgtype.Timestamp
}

type Greenprint struct {
	ID                  int64
	ImageKey            string
	Title               string
	Description         string
	SustainabilityScore string
	EstimatedTime       string
	CreatedAt           pgtype.Timestamp
	ItemID              int64
}

type Habit struct {
	ID          int64
	PacketID    int64
	Name        string
	Description string
	Difficulty  string
	Locked      bool
	Weight      int32
}

type History struct {
	ID        int64
	UserID    int64
	Name      string
	Type      string
	Category  string
	Amount    int32
	CreatedAt pgtype.Timestamp
}

type Item struct {
	ID          int64
	ScanID      int64
	Name        string
	Description string
	Value       string
	CreatedAt   pgtype.Timestamp
	UserID      int64
}

type Job struct {
	ID          int64
	Queue       string
	Payload     string
	Attempts    int16
	ReservedAt  pgtype.Int4
	AvailableAt int32
	CreatedAt   int32
}

type JobBatch struct {
	ID           string
	Name         string
	TotalJobs    int32
	PendingJobs  int32
	FailedJobs   int32
	FailedJobIds string
	Options      pgtype.Text
	CancelledAt  pgtype.Int4
	CreatedAt    int32
	FinishedAt   pgtype.Int4
}

type Log struct {
	ID        int64
	UserID    int64
	Text      string
	IsSystem  bool
	IsPrivate bool
	CreatedAt pgtype.Timestamp
}

type Material struct {
	ID           int64
	Name         string
	Description  string
	Price        int32
	Quantity     int32
	GreenprintID int64
}

type Memory struct {
	ID          int64
	UserID      int64
	FileKey     string
	Description string
	CreatedAt   pgtype.Timestamp
}

type Migration struct {
	ID        int32
	Migration string
	Batch     int32
}

type Packet struct {
	ID            int64
	UserID        int64
	Name          string
	Target        string
	Description   string
	CompletedTask int32
	ExpectedTask  int32
	TaskPerDay    int32
	Completed     bool
	CreatedAt     pgtype.Timestamp
}

type Participation struct {
	ID          int64
	ChallengeID int64
	UserID      int64
	MemoryID    int64
	CreatedAt   pgtype.Timestamp
}

type PasswordResetToken struct {
	Email     string
	Token     string
	CreatedAt pgtype.Timestamp
}

type Profile struct {
	ID         int64
	UserID     int64
	CurrentExp int64
	ExpNeeded  int64
	Level      int32
	Points     int64
	ProfileKey string
}

type Quest struct {
	ID              int64
	DetailID        int64
	CodeID          string
	Location        string
	Latitude        float64
	Longitude       float64
	MaxContributors int32
	Finished        bool
	Clue            pgtype.Text
}

type Recap struct {
	ID             int64
	UserID         int64
	Summary        string
	Tips           string
	AssignedTask   int32
	CompletedTask  int32
	CompletionRate string
	GrowthRating   string
	Type           string
	CreatedAt      pgtype.Timestamp
}

type RecapDetail struct {
	ID             int64
	MonthlyRecapID int64
	Challenges     int32
	Events         int32
	Quests         int32
	Treasures      int32
	LongestStreak  int32
	CreatedAt      pgtype.Timestamp
}

type Scan struct {
	ID          int64
	UserID      int64
	Title       string
	Description string
	CreatedAt   pgtype.Timestamp
	ImageKey    pgtype.Text
}

type Session struct {
	ID           string
	UserID       pgtype.Int8
	IpAddress    pgtype.Text
	UserAgent    pgtype.Text
	Payload      string
	LastActivity int32
}

type Statistic struct {
	ID            int64
	UserID        int64
	Challenges    int32
	Events        int32
	Quests        int32
	Treasures     int32
	LongestStreak int32
	TreeGrown     int32
}

type Step struct {
	ID           int64
	GreenprintID int64
	Description  string
	CreatedAt    pgtype.Timestamp
}

type Task struct {
	ID          int64
	HabitID     int64
	UserID      int64
	PacketID    int64
	Name        string
	Description string
	Difficulty  string
	Completed   bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Tool struct {
	ID           int64
	GreenprintID int64
	Name         string
	Description  string
	Price        int32
	CreatedAt    pgtype.Timestamp
}

type Treasure struct {
	ID        int64
	Name      string
	PointGain int64
	CodeID    string
	Claimed   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID              int64
	Name            string
	Username        string
	Email           string
	EmailVerifiedAt pgtype.Timestamp
	Password        string
	IsAdmin         bool
	RememberToken   pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}
